spring:
  application:
    name: payment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bank?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ss123000
management:
  endpoints:
    web:
      exposure:
        # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点
        include: "*"
  metrics:
    tags: # 通用标签
      application: ${spring.application.name}
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 9098
  tomcat:
    accesslog:
      enabled: true
      file-date-format: .yyyy-MM-dd
      suffix: .log
      prefix: access_log
      directory: tomcat_log
      pattern: common
    basedir: D:/tmp
logging:
  level:
    org.apache.tomcat: DEBUG
    org.apache.catalina: DEBUG
